export interface TerminoGlosario {
  termino: string; queEs: string; ejemplo: string; donde: string; grupo: string;
}

export const GLOSARIO: TerminoGlosario[] = [
  { grupo: "La inversión y los costos", termino: "CAPEX (inversión)",
    queEs: "El capital que se coloca UNA VEZ para construir o adquirir un bien que va a durar muchos años: el muelle, los silos, una grúa. No es un gasto del ejercicio: es un activo que permanece.",
    ejemplo: "Construir el muelle cuesta 25 millones. Se desembolsan durante la obra y después el muelle presta servicio 30 años.",
    donde: "Filas de CAPEX en el flujo. Se carga en la tabla anual de cada unidad." },
  { grupo: "La inversión y los costos", termino: "OPEX (costo de operar)",
    queEs: "Lo que cuesta mantener el negocio en funcionamiento TODOS LOS AÑOS: sueldos, energía, mantenimiento, seguros. Si se interrumpe su pago, el puerto deja de operar.",
    ejemplo: "Los sueldos de la dotación son 2,2 millones por año, todos los años.",
    donde: "Filas de OPEX fijo, variable y total en el flujo de cada unidad." },
  { grupo: "La inversión y los costos", termino: "OPEX fijo",
    queEs: "La parte del costo que se devenga igual se opere 1 tonelada o 3 millones: dotación estable, seguros, mantenimiento programado.",
    ejemplo: "Aunque no recale ningún buque en enero, los sueldos se abonan igual.",
    donde: "Parámetros de cada unidad." },
  { grupo: "La inversión y los costos", termino: "OPEX variable",
    queEs: "La parte del costo que crece con el volumen operado: combustible, horas extra, insumos. Se expresa en dólares por tonelada.",
    ejemplo: "Operar una tonelada cuesta 1,58 dólares. Al duplicar el volumen, ese costo se duplica.",
    donde: "Parámetros de cada unidad; puede sustituirse año por año." },
  { grupo: "La inversión y los costos", termino: "Canon",
    queEs: "La contraprestación que se abona al titular del predio o al Estado por el derecho a operar. Puede ser fija, por tonelada, o un porcentaje de la facturación.",
    ejemplo: "Un canon del 2% sobre la facturación: con 50 millones facturados, se abona 1 millón.",
    donde: "Bloque Canon en cada unidad." },

  { grupo: "Medición del resultado", termino: "Ingresos brutos",
    queEs: "El total de ingresos por la prestación del servicio, antes de deducir concepto alguno. Es la facturación.",
    ejemplo: "3 millones de toneladas a 8 dólares la tonelada = 24 millones de facturación.",
    donde: "Fila Ingresos brutos, en el flujo de cada unidad y en el consolidado." },
  { grupo: "Medición del resultado", termino: "EBITDA",
    queEs: "El resultado que genera la operación, antes de considerar la inversión y los impuestos. Es Ingresos menos OPEX menos Canon. Responde si el negocio, en sí mismo, genera excedente.",
    ejemplo: "Facturación 24 millones, costo operativo 10 y canon 1. EBITDA = 13 millones.",
    donde: "Fila EBITDA. Es el indicador que evalúa un banco." },
  { grupo: "Medición del resultado", termino: "Depreciación",
    queEs: "La imputación contable del desgaste de la inversión. Como el muelle tiene una vida útil de 30 años, cada ejercicio absorbe una parte. NO es una erogación: el desembolso ocurrió al construirlo. Reduce la base imponible.",
    ejemplo: "Un silo de 20 millones con vida útil de 20 años se deprecia 1 millón por año.",
    donde: "Fila Depreciación. La vida útil se carga en Parámetros generales." },
  { grupo: "Medición del resultado", termino: "Amortización acelerada",
    queEs: "Una autorización legal para depreciar en menos ejercicios. No modifica el impuesto total de toda la vida del proyecto, pero lo anticipa. Como el dinero tiene valor tiempo, eso mejora la rentabilidad.",
    ejemplo: "Con RIGI, una inversión de 30 años se deprecia en 18.",
    donde: "Opción en el bloque RIGI." },
  { grupo: "Medición del resultado", termino: "EBIT (resultado operativo)",
    queEs: "EBITDA menos depreciación. Es el resultado una vez reconocido el desgaste de lo invertido. Sobre este importe se determina el impuesto.",
    ejemplo: "EBITDA 13 millones menos depreciación 4 = EBIT 9 millones.",
    donde: "Fila EBIT." },
  { grupo: "Medición del resultado", termino: "NOPAT",
    queEs: "El resultado operativo después del impuesto, con independencia de cómo se financie el proyecto. Es lo que queda disponible para todos los proveedores de fondos, accionistas o entidades financieras.",
    ejemplo: "EBIT 9 millones menos impuesto 2,25 = NOPAT 6,75 millones.",
    donde: "Fila NOPAT en el consolidado." },
  { grupo: "Medición del resultado", termino: "Margen EBITDA",
    queEs: "Qué porcentaje de la facturación queda como resultado operativo. Permite comparar negocios de distinta escala.",
    ejemplo: "EBITDA 13 sobre facturación 24 = 54% de margen.",
    donde: "Indicador del Resumen y columna en la tabla por unidad." },

  { grupo: "Los flujos de caja", termino: "Flujo de caja",
    queEs: "Los fondos que efectivamente ingresan y egresan de la cuenta bancaria cada ejercicio. Difiere del resultado contable: la depreciación reduce el resultado sin erogación, y la inversión genera erogación sin afectar el resultado.",
    ejemplo: "En 2026 el proyecto no factura y desembolsa 34 millones en obra: el flujo de ese ejercicio es −34 millones.",
    donde: "Filas FCFF y FCFE." },
  { grupo: "Los flujos de caja", termino: "FCFF (flujo libre del proyecto)",
    queEs: "Los fondos que genera el proyecto antes de definir su estructura de financiamiento: NOPAT más depreciación menos inversión menos las tasas que se erogan. Es la fila central del modelo: sobre ella se determina la TIR.",
    ejemplo: "NOPAT 6,75 más depreciación 4 menos inversión 0 = FCFF 10,75 millones.",
    donde: "Fila FCFF CONSOLIDADO y el gráfico de barras del Resumen." },
  { grupo: "Los flujos de caja", termino: "FCFE (flujo del accionista)",
    queEs: "El remanente para el accionista después de atender intereses y amortizaciones de la deuda. Si el proyecto no toma deuda, coincide con el FCFF.",
    ejemplo: "FCFF 10,75 menos intereses 1,2 menos amortización 2 = FCFE 7,55 millones.",
    donde: "Fila FCFE CONSOLIDADO." },

  { grupo: "Criterios de decisión", termino: "TIR (tasa interna de retorno)",
    queEs: "El rendimiento anual que ofrece el proyecto, expresado en porcentaje. Sintetiza en un solo indicador toda la serie de flujos.",
    ejemplo: "Una TIR del 15% significa que el capital invertido rinde 15% anual, en dólares.",
    donde: "Indicador principal del Resumen y columna por unidad." },
  { grupo: "Criterios de decisión", termino: "Payback (período de recupero)",
    queEs: "El ejercicio en que se recupera la totalidad del capital invertido: el momento en que el flujo acumulado pasa de negativo a positivo.",
    ejemplo: "Si se invierte hasta 2029 y el acumulado se vuelve positivo en 2034, el recupero es 2034.",
    donde: "Indicador del Resumen y gráfico de FCFF acumulado." },
  { grupo: "Criterios de decisión", termino: "DSCR (cobertura del servicio de deuda)",
    queEs: "Cuántas veces el resultado operativo cubre el servicio de deuda del ejercicio. 1,0 indica cobertura exacta. Las entidades financieras suelen exigir 1,3 como mínimo.",
    ejemplo: "EBITDA 13 millones y servicio anual 8 millones: DSCR = 1,63. Cobertura holgada.",
    donde: "Fila DSCR en el flujo consolidado." },
  { grupo: "Criterios de decisión", termino: "Aporte incremental",
    queEs: "En cuánto mejora o deteriora la rentabilidad del proyecto la incorporación de una unidad de negocio. Es el criterio correcto para decidir si conviene sumar fertilizantes o cargas generales.",
    ejemplo: "El proyecto sin fertilizantes rinde 11%; con fertilizantes, 15%. La unidad aporta 4 puntos.",
    donde: "Columna 'Aporte a la TIR' en la tabla por unidad del Resumen." },

  { grupo: "Impuestos en Argentina", termino: "Impuesto a las Ganancias",
    queEs: "El impuesto sobre el resultado de la sociedad. La alícuota general es 35%; bajo el RIGI se reduce a 25%. Si el ejercicio arroja quebranto, no se determina impuesto.",
    ejemplo: "EBIT de 9 millones al 25% = 2,25 millones de impuesto.",
    donde: "Filas de Ganancias en el flujo consolidado." },
  { grupo: "Impuestos en Argentina", termino: "RIGI (Ley 27.742)",
    queEs: "Un régimen especial para grandes inversiones: alícuota reducida del impuesto a las ganancias, amortización acelerada y exenciones provinciales y municipales por varios años. En el modelo se activa o desactiva.",
    ejemplo: "Con RIGI la alícuota de ganancias es 25% en lugar de 35%: 10 puntos menos sobre todo el resultado.",
    donde: "Bloque RIGI en Parámetros generales." },
  { grupo: "Impuestos en Argentina", termino: "IIBB (Ingresos Brutos)",
    queEs: "Impuesto provincial que se liquida como un porcentaje de la FACTURACIÓN, con independencia del resultado. Bajo RIGI, Santa Fe lo exime por 10 años.",
    ejemplo: "5% sobre 24 millones representaría 1,2 millones anuales que no se erogan.",
    donde: "Fila informativa de ahorro por IIBB exento." },
  { grupo: "Impuestos en Argentina", termino: "DREI (tasa municipal)",
    queEs: "La tasa que percibe el municipio de Timbúes por la habilitación de la actividad. Un por mil sobre la facturación, con un importe mínimo mensual en pesos. Exenta por 10 años con RIGI.",
    ejemplo: "Finalizada la exención: 5 por mil sobre 24 millones = 120 mil dólares por año.",
    donde: "Fila DREI. Los parámetros están en Parámetros generales." },
  { grupo: "Impuestos en Argentina", termino: "IDyCB (impuesto al cheque)",
    queEs: "Se percibe sobre cada acreditación y cada débito en la cuenta bancaria: 0,6% en cada caso. Bajo RIGI puede computarse a cuenta del impuesto a las ganancias.",
    ejemplo: "Un movimiento de 34 millones genera unos 408 mil dólares de impuesto al cheque.",
    donde: "Filas de IDyCB pagado y recuperado." },
  { grupo: "Impuestos en Argentina", termino: "IVA crédito fiscal (CERTIVA)",
    queEs: "El IVA facturado en la compra de equipos y materiales de obra. NO constituye un costo: se recupera contra el IVA de las ventas. Computarlo como costo es el error más frecuente en los modelos de inversión.",
    ejemplo: "Una compra de 100 millones contiene 21 millones de IVA, que luego se recuperan.",
    donde: "Fila informativa de IVA de inversiones. No afecta el flujo." },
  { grupo: "Impuestos en Argentina", termino: "Ahorro informativo (MEMO)",
    queEs: "Un beneficio que consiste en no erogar un concepto. No representa un ingreso, de modo que no integra el flujo de caja. Se expone por separado para cuantificar su valor.",
    ejemplo: "La exención de IIBB evita erogar 1,2 millones por año, pero esos fondos nunca ingresan a la cuenta: simplemente no egresan.",
    donde: "Las filas marcadas [Informativo] en el flujo consolidado." },

  { grupo: "El negocio portuario", termino: "Los cinco rubros de la tarifa",
    queEs: "La facturación al cliente se descompone en cinco conceptos: uso de muelle, estibaje, manipuleo, almacenaje y calada. Cada carga puede tener una tarifa distinta en cada uno.",
    ejemplo: "Descargar, almacenar y despachar una tonelada de fertilizante se factura unos 30 dólares en total.",
    donde: "Grilla de flujos de cada unidad." },
  { grupo: "El negocio portuario", termino: "Uso de muelle",
    queEs: "La contraprestación por ocupar el muelle mientras el buque carga o descarga. En rigor no se vende una tonelada: se vende tiempo de muelle, y se factura por tonelada.",
    ejemplo: "Referencia de la zona: 0,37 dólares por tonelada de registro del buque, por día de estadía.",
    donde: "Columna 'Muelle USD/tn' en la grilla de flujos." },
  { grupo: "El negocio portuario", termino: "Estibaje",
    queEs: "La operación de carga o descarga del buque: grúas, cintas, cuadrillas. Es el concepto de mayor costo y el que más varía entre productos.",
    ejemplo: "Descargar acero se factura muy por encima de embarcar granos, porque se opera bulto por bulto.",
    donde: "Columna 'Estibaje USD/tn'." },
  { grupo: "El negocio portuario", termino: "Ocupación de muelle",
    queEs: "Qué porcentaje del año permanece ocupado el muelle. Es la restricción física del negocio: se puede comercializar cualquier volumen, pero con el muelle saturado no ingresa un buque más.",
    ejemplo: "Con una ocupación del 85% la terminal está saturada: cualquier demora genera cola de espera de buques.",
    donde: "Gráfico de ocupación en el Resumen y fila en el flujo consolidado." },
  { grupo: "El negocio portuario", termino: "Parcela",
    queEs: "Las toneladas que carga o descarga un buque en cada recalada. Cuanto menor es la parcela, más recaladas se requieren para el mismo volumen, y mayor es la ocupación del muelle.",
    ejemplo: "Un granelero puede transportar 27.000 toneladas; uno de fertilizante, 20.000.",
    donde: "Parámetros de ocupación de cada unidad." },
  { grupo: "El negocio portuario", termino: "Sitios de atraque",
    queEs: "Cuántos buques pueden permanecer amarrados y en operación simultáneamente. Divide la ocupación: con 2 sitios el mismo tráfico ocupa la mitad. Es la variable que define si corresponde ampliar el muelle.",
    ejemplo: "Con las tres unidades en un solo sitio la ocupación alcanzaba 438%; con 3 sitios desciende a 59%.",
    donde: "Parámetros generales." },
  { grupo: "El negocio portuario", termino: "Take-or-pay",
    queEs: "Un contrato por el cual el cliente abona un volumen mínimo aunque no lo utilice. Establece un piso de facturación para la terminal.",
    ejemplo: "El cliente se compromete a 500.000 toneladas: si despacha 400.000, abona 500.000 igual.",
    donde: "Parámetros de cada unidad." },
  { grupo: "El negocio portuario", termino: "Curva de maduración (ramp up)",
    queEs: "Qué porcentaje de la capacidad se alcanza en los primeros ejercicios, mientras se ajustan los procesos y se capta la cartera de clientes. Ninguna terminal inicia al 100%.",
    ejemplo: "El primer año se opera al 70% de lo previsto: el coeficiente es 0,70.",
    donde: "Bloque de maduración en Parámetros generales." },
  { grupo: "El negocio portuario", termino: "Costos comunes y prorrateo",
    queEs: "Costos que benefician a las tres unidades simultáneamente. Deben distribuirse con algún criterio, de lo contrario ninguna los absorbe. Lo que depende del muelle se distribuye por tiempo de uso, nunca por toneladas.",
    ejemplo: "El dragado cuesta 500 mil anuales y se distribuye 60% agrograneles, 20% fertilizantes y líquidos, 20% cargas.",
    donde: "Hoja de Costos comunes." },
  { grupo: "El negocio portuario", termino: "Structuring fee",
    queEs: "La comisión por estructurar la operación: conformar el sindicato de socios, estructurar el financiamiento y tramitar el RIGI. Se percibe por única vez.",
    ejemplo: "10 millones que percibe un socio y desembolsan los otros tres en partes iguales.",
    donde: "Parámetros generales y panel de Inversores." },
  { grupo: "El negocio portuario", termino: "Pari passu",
    queEs: "Expresión latina: 'en igualdad de condiciones'. Todos los socios aportan y perciben en la misma proporción que su participación, sin prelación alguna.",
    ejemplo: "Un socio con el 55% aporta el 55% de la inversión y percibe el 55% del excedente distribuible.",
    donde: "Panel de Inversores." },
];

export const MANUAL: { titulo: string; parrafos: string[] }[] = [
  { titulo: "Qué pregunta responde esta aplicación", parrafos: [
    "Una sola: si se destina esta cantidad de capital a construir el puerto, y luego se lo opera durante 30 años con estas tarifas, estos costos y estos impuestos, ¿qué retorno genera y en qué plazo? Todo lo demás existe para responder eso con números trazables en lugar de estimaciones intuitivas.",
    "La cadena de razonamiento es siempre la misma: toneladas × tarifa = ingresos. Ingresos − costos operativos − canon = EBITDA. EBITDA − depreciación = EBIT, que constituye la base imponible. EBIT − impuesto + depreciación (que no fue una erogación) − inversión = flujo de caja. Y el flujo de caja de los 31 ejercicios, sintetizado en un solo indicador, es la TIR.",
  ]},
  { titulo: "Las tres unidades de negocio", parrafos: [
    "Agrograneles: granos que ingresan por camión o vagón, se acondicionan, se almacenan en silos y se embarcan. Es la unidad de mayor volumen y de menor tarifa por tonelada.",
    "Fertilizantes y líquidos: fertilizantes sólidos, UAN y aceites. Se descargan del buque, se almacenan en depósito o tanques y se despachan. Menor volumen que granos, con una tarifa por tonelada sensiblemente superior.",
    "Cargas generales: acero, bobinas, mineral de hierro, soda ash, trasbordos y barcazas. Volumen reducido, tarifa elevada y operación lenta: ocupa mucho muelle por tonelada.",
    "Las tres se calculan con la misma estructura, de modo que quien comprende una comprende las tres, y el consolidado resulta de una suma directa.",
  ]},
  { titulo: "Los dos métodos de tarifa", parrafos: [
    "Cada unidad define cómo se determinan sus ingresos, y ambas opciones pueden convivir: agrograneles puede usar un método y las otras dos, el otro.",
    "Método 1, grilla de flujos: se detalla cada corriente comercial —por ejemplo, 'ingreso de fertilizante por buque con destino a depósito'— con su volumen del primer ejercicio, su tasa de crecimiento, su tope y las cinco tarifas aplicables. El modelo consolida todos los flujos. Corresponde cuando la unidad opera una mezcla de cargas, cada una con su tarifa.",
    "Método 2, escalonado por volumen: se proyecta un volumen único para toda la unidad y la tarifa desciende por tramos a medida que ese volumen crece. Corresponde cuando existe un acuerdo comercial con precios por tramo. El campo determinante es 'Volumen total a operar del titular': en cero, todo se factura a tarifa base porque opera un tercero; con un valor mayor a cero, el titular opera hasta ese límite con las tarifas por tramo y el excedente vuelve a tarifa base.",
  ]},
  { titulo: "La restricción que más se omite: el muelle", parrafos: [
    "Se puede comercializar cualquier volumen, pero con el muelle ocupado no ingresa un buque más. El modelo determina, para cada unidad, cuántas recaladas se requieren y cuántos días permanece amarrado cada buque según el rendimiento de carga y el tiempo improductivo por condiciones meteorológicas o maniobras. Con eso obtiene qué porcentaje del año permanece ocupado el muelle.",
    "Si las tres unidades en conjunto superan el umbral, la aplicación emite una alerta. Por encima de ese nivel cualquier demora genera cola de espera de buques y el volumen comprometido deja de ser sostenible: corresponde ampliar el muelle —lo que implica mayor CAPEX— o rechazar carga.",
    "Por la misma razón, los costos del muelle se distribuyen entre las unidades por tiempo de uso y no por toneladas: una tonelada de acero ocupa muchísimo más muelle que una de granos, y prorratear por tonelada haría que granos subsidie al resto.",
  ]},
  { titulo: "El tratamiento impositivo", parrafos: [
    "Todos los impuestos se determinan una sola vez, sobre el resultado consolidado de las tres unidades. El fundamento es simple: el sujeto del impuesto es la sociedad, no cada unidad por separado, y el quebranto de una unidad compensa el resultado positivo de otra. Las filas de impuesto que aparecen en cada unidad son exclusivamente informativas.",
    "Los ahorros de IIBB y de la tasa municipal se exponen como informativos porque la exención significa que no se eroga el concepto, no que ingresen fondos: no integran el flujo de caja. El IVA de las inversiones también es informativo: constituye crédito fiscal, no costo, y computarlo como costo es el error más frecuente en los modelos de inversión.",
    "El RIGI se trata como una opción, no como un supuesto. Corresponde correr el modelo con el régimen activado y desactivado, y exponer ambas TIR. La diferencia entre ellas es exactamente cuánto vale el régimen para este proyecto, y ese es el argumento ante el directorio.",
    "Las alícuotas y los plazos cargados son los vigentes al momento de elaborar el modelo. La normativa se modifica: antes de exponer cualquier cifra corresponde confirmarla con el asesor impositivo. Esta aplicación realiza el cálculo; no constituye asesoramiento fiscal.",
  ]},
  { titulo: "Cómo interpretar los resultados", parrafos: [
    "EBITDA positivo con TIR baja: la operación es viable pero la inversión resulta excesiva para el resultado que genera. La discusión no es comercial sino de ingeniería y de etapabilidad.",
    "EBITDA negativo: la unidad opera a pérdida. Ninguna estructura financiera, ningún beneficio impositivo y ninguna extensión de plazo lo corrigen. Corresponde revisar tarifas o costos.",
    "DSCR por debajo de 1,3: es probable que la entidad financiera no otorgue el crédito, o que requiera garantías adicionales. Se resuelve con menor endeudamiento o mayor plazo.",
    "Ocupación de muelle por encima del umbral: el modelo está proyectando un volumen que físicamente no ingresa. Cualquier TIR calculada sobre ese volumen carece de sustento.",
  ]},
  { titulo: "Cómo se registra el trabajo", parrafos: [
    "Cada modificación de un campo recalcula todo el modelo de inmediato, pero nada se registra hasta confirmar con Guardar. Antes de guardar se puede revisar exactamente qué campos se modificaron, con su valor anterior y el nuevo.",
    "Cada registro genera una versión nueva, con el detalle de cambios, un comentario opcional y los indicadores de ese momento. Nada se sobrescribe ni se elimina: el historial completo queda disponible para auditar quién modificó qué supuesto y cuándo.",
    "Se pueden mantener varios escenarios en paralelo —por ejemplo, uno con RIGI y otro sin RIGI— y compararlos.",
  ]},
  { titulo: "Qué valores corresponde validar", parrafos: [
    "Todos los valores del escenario base son preliminares. Como mínimo corresponde validar: las tarifas de los cinco rubros y los volúmenes de cada flujo con Comercial; el OPEX fijo y variable de cada unidad, que debería derivarse de dotación por mano y turno, mantenimiento como porcentaje del CAPEX de cada activo y energía, con Operaciones; las curvas de CAPEX con Ingeniería; los porcentajes de prorrateo con Control de Gestión; y el bloque RIGI con el asesor impositivo.",
    "El tipo de cambio oficial y el mínimo mensual del DREI están en cero: corresponde completarlos, dado que sin ellos el DREI se determina solo por alícuota y queda subestimado.",
  ]},
];
