export interface TerminoGlosario {
  termino: string; queEs: string; ejemplo: string; donde: string; grupo: string;
}

export const GLOSARIO: TerminoGlosario[] = [
  { grupo: "La plata que se pone y la que se gasta", termino: "CAPEX (inversión)",
    queEs: "La plata que se pone UNA VEZ para construir o comprar algo que va a durar muchos años: el muelle, los silos, una grúa. No es un gasto del año: es un activo que queda.",
    ejemplo: "Construir el muelle cuesta 25 millones. Se pagan durante la obra y después el muelle sirve 30 años.",
    donde: "Filas de CAPEX en el flujo. Se carga en la tabla anual de cada unidad." },
  { grupo: "La plata que se pone y la que se gasta", termino: "OPEX (costo de operar)",
    queEs: "Lo que cuesta hacer funcionar el negocio TODOS LOS AÑOS: sueldos, energía, mantenimiento, seguros. Si dejás de pagarlo, el puerto para.",
    ejemplo: "Los sueldos de la dotación son 2,2 millones por año, todos los años.",
    donde: "Filas de OPEX fijo, variable y total en el flujo de cada unidad." },
  { grupo: "La plata que se pone y la que se gasta", termino: "OPEX fijo",
    queEs: "La parte del costo que se paga igual muevas 1 tonelada o 3 millones: dotación estable, seguros, mantenimiento programado.",
    ejemplo: "Aunque no llegue ningún barco en enero, los sueldos se pagan igual.",
    donde: "Parámetros de cada unidad." },
  { grupo: "La plata que se pone y la que se gasta", termino: "OPEX variable",
    queEs: "La parte del costo que crece con el volumen: combustible, horas extra, insumos. Se expresa en dólares por tonelada.",
    ejemplo: "Mover una tonelada cuesta 1,58 dólares. Si movemos el doble, ese costo se duplica.",
    donde: "Parámetros de cada unidad; se puede pisar año por año." },
  { grupo: "La plata que se pone y la que se gasta", termino: "Canon",
    queEs: "Lo que se le paga al dueño de la tierra o al Estado por el derecho a operar ahí. Puede ser fijo, por tonelada, o un porcentaje de lo facturado.",
    ejemplo: "Un canon de 2% sobre la facturación: si facturamos 50 millones, se pagan 1 millón.",
    donde: "Bloque Canon en cada unidad." },

  { grupo: "Cómo se mide si el negocio gana", termino: "Ingresos brutos",
    queEs: "Toda la plata que entra por vender el servicio, antes de descontar nada. Es la facturación.",
    ejemplo: "3 millones de toneladas a 8 dólares la tonelada = 24 millones de facturación.",
    donde: "Fila Ingresos brutos, en el flujo de cada unidad y en el consolidado." },
  { grupo: "Cómo se mide si el negocio gana", termino: "EBITDA",
    queEs: "Lo que gana el negocio OPERANDO, antes de contar la inversión y los impuestos. Es Ingresos menos OPEX menos Canon. Responde: el negocio en sí mismo, ¿deja plata?",
    ejemplo: "Facturamos 24 millones, operar cuesta 10 y el canon 1. EBITDA = 13 millones.",
    donde: "Fila EBITDA. Es el número que mira un banco." },
  { grupo: "Cómo se mide si el negocio gana", termino: "Depreciación",
    queEs: "El desgaste contable de la inversión. Como el muelle dura 30 años, cada año se 'gasta' una parte. NO es plata que sale: la plata salió cuando se construyó. Sirve para pagar menos impuesto.",
    ejemplo: "Un silo de 20 millones que dura 20 años se deprecia 1 millón por año.",
    donde: "Fila Depreciación. La vida útil se carga en Parámetros generales." },
  { grupo: "Cómo se mide si el negocio gana", termino: "Amortización acelerada",
    queEs: "Un permiso legal para depreciar más rápido. No cambia el impuesto total de toda la vida del proyecto, pero lo adelanta. Como la plata vale más hoy que mañana, eso mejora la rentabilidad.",
    ejemplo: "Con RIGI, una inversión de 30 años se deprecia en 18.",
    donde: "Interruptor en el bloque RIGI." },
  { grupo: "Cómo se mide si el negocio gana", termino: "EBIT (resultado operativo)",
    queEs: "EBITDA menos depreciación. Es la ganancia una vez que se reconoce el desgaste de lo invertido. Sobre este número se calcula el impuesto.",
    ejemplo: "EBITDA 13 millones menos depreciación 4 = EBIT 9 millones.",
    donde: "Fila EBIT." },
  { grupo: "Cómo se mide si el negocio gana", termino: "NOPAT",
    queEs: "La ganancia operativa después del impuesto, sin considerar cómo se financia el proyecto. Es lo que queda para todos los que pusieron plata, socios o bancos.",
    ejemplo: "EBIT 9 millones menos impuesto 2,25 = NOPAT 6,75 millones.",
    donde: "Fila NOPAT en el consolidado." },
  { grupo: "Cómo se mide si el negocio gana", termino: "Margen EBITDA",
    queEs: "Qué porcentaje de lo que facturás te queda como ganancia operativa. Sirve para comparar negocios de distinto tamaño.",
    ejemplo: "EBITDA 13 sobre facturación 24 = 54% de margen.",
    donde: "Tarjeta en el Resumen y columna en la tabla por unidad." },

  { grupo: "La plata que entra y sale de verdad", termino: "Flujo de caja",
    queEs: "La plata que efectivamente entra y sale de la cuenta bancaria cada año. Es distinto de la ganancia contable: la depreciación resta ganancia pero no saca plata, y la inversión saca plata pero no resta ganancia.",
    ejemplo: "En 2026 el proyecto factura 0 y gasta 34 millones construyendo: el flujo de ese año es −34 millones.",
    donde: "Filas FCFF y FCFE." },
  { grupo: "La plata que entra y sale de verdad", termino: "FCFF (flujo libre del proyecto)",
    queEs: "La plata que genera el proyecto antes de decidir quién lo financia: NOPAT más depreciación menos inversión menos las tasas que salen de caja. Es LA fila del modelo: sobre ella se calcula la TIR.",
    ejemplo: "NOPAT 6,75 más depreciación 4 menos inversión 0 = FCFF 10,75 millones.",
    donde: "Fila FCFF CONSOLIDADO y el gráfico de barras del Resumen." },
  { grupo: "La plata que entra y sale de verdad", termino: "FCFE (flujo del accionista)",
    queEs: "Lo que le queda al socio después de pagarle al banco los intereses y las cuotas. Si el proyecto no tiene deuda, es igual al FCFF.",
    ejemplo: "FCFF 10,75 menos intereses 1,2 menos cuota 2 = FCFE 7,55 millones.",
    donde: "Fila FCFE CONSOLIDADO." },

  { grupo: "Cómo se decide si conviene", termino: "TIR (tasa interna de retorno)",
    queEs: "El rendimiento anual que da el proyecto, en porcentaje, como si fuera un plazo fijo. Resume en un solo número toda la serie de flujos.",
    ejemplo: "Una TIR de 15% significa que la plata invertida rinde 15% por año, en dólares.",
    donde: "Tarjeta principal del Resumen y columna por unidad." },
  { grupo: "Cómo se decide si conviene", termino: "Payback",
    queEs: "En qué año se recupera toda la plata invertida: el momento en que el flujo acumulado pasa de negativo a positivo.",
    ejemplo: "Si se invierte hasta 2029 y el acumulado se hace positivo en 2034, el payback es 2034.",
    donde: "Tarjeta del Resumen y gráfico de FCFF acumulado." },
  { grupo: "Cómo se decide si conviene", termino: "DSCR (cobertura de deuda)",
    queEs: "Cuántas veces alcanza la ganancia operativa para pagar la cuota del banco ese año. 1,0 = alcanza justo. Los bancos suelen exigir 1,3 como mínimo para prestar.",
    ejemplo: "EBITDA 13 millones y cuota anual 8 millones: DSCR = 1,63. Cómodo.",
    donde: "Fila DSCR en el flujo consolidado." },
  { grupo: "Cómo se decide si conviene", termino: "Aporte incremental",
    queEs: "Cuánto mejora o empeora la rentabilidad del proyecto por agregarle una unidad de negocio. Es la forma correcta de decidir si conviene sumar fertilizantes o cargas generales.",
    ejemplo: "El proyecto sin fertilizantes da 11%; con fertilizantes da 15%. La unidad aporta 4 puntos.",
    donde: "Columna 'Aporte a la TIR' en la tabla por unidad del Resumen." },

  { grupo: "Impuestos en Argentina", termino: "Impuesto a las Ganancias",
    queEs: "El impuesto sobre la ganancia de la empresa. La alícuota general es 35%; bajo el RIGI baja a 25%. Si el año da pérdida, no se paga.",
    ejemplo: "EBIT de 9 millones al 25% = 2,25 millones de impuesto.",
    donde: "Filas de Ganancias en el flujo consolidado." },
  { grupo: "Impuestos en Argentina", termino: "RIGI (Ley 27.742)",
    queEs: "Un régimen especial para grandes inversiones: menos impuesto a las ganancias, depreciar más rápido, y exenciones provinciales y municipales por varios años. En el modelo es un interruptor.",
    ejemplo: "Con RIGI la tasa de ganancias es 25% en vez de 35%: 10 puntos menos sobre toda la ganancia.",
    donde: "Bloque RIGI en Parámetros generales." },
  { grupo: "Impuestos en Argentina", termino: "IIBB (Ingresos Brutos)",
    queEs: "Impuesto provincial que se paga como un porcentaje de lo FACTURADO, se gane o se pierda. Bajo RIGI, Santa Fe lo exime por 10 años.",
    ejemplo: "5% sobre 24 millones serían 1,2 millones por año que NO se pagan.",
    donde: "Fila MEMO de ahorro por IIBB exento." },
  { grupo: "Impuestos en Argentina", termino: "DREI (tasa municipal)",
    queEs: "La tasa que cobra el municipio de Timbúes por tener la actividad habilitada. Un por mil de la facturación, con un pago mínimo mensual en pesos. Exenta por 10 años con RIGI.",
    ejemplo: "Terminada la exención: 5 por mil sobre 24 millones = 120 mil dólares por año.",
    donde: "Fila DREI. Los parámetros están en Parámetros generales." },
  { grupo: "Impuestos en Argentina", termino: "IDyCB (impuesto al cheque)",
    queEs: "Se cobra cada vez que entra o sale plata de una cuenta bancaria: 0,6% al debitar y 0,6% al acreditar. Bajo RIGI se puede descontar del impuesto a las ganancias.",
    ejemplo: "Un pago de 34 millones genera unos 408 mil dólares de impuesto al cheque.",
    donde: "Filas de IDyCB pagado y recuperado." },
  { grupo: "Impuestos en Argentina", termino: "IVA crédito fiscal (CERTIVA)",
    queEs: "El IVA que se paga al comprar los equipos y materiales de la obra. NO es un costo: se recupera contra el IVA de las ventas. Confundirlo con un costo es el error más común en los modelos de inversión.",
    ejemplo: "Una compra de 100 millones tiene 21 millones de IVA, que después se recuperan.",
    donde: "Fila MEMO de IVA de inversiones. No afecta el flujo." },
  { grupo: "Impuestos en Argentina", termino: "Ahorro tipo MEMO",
    queEs: "Un beneficio que consiste en NO pagar algo. No es plata que entra, así que no se suma al flujo de caja. Se muestra aparte para poder cuantificar cuánto vale.",
    ejemplo: "La exención de IIBB ahorra 1,2 millones por año, pero esa plata nunca entra a la cuenta: simplemente no sale.",
    donde: "Las filas marcadas [MEMO] en el flujo consolidado." },

  { grupo: "El negocio portuario", termino: "Los cinco rubros de la tarifa",
    queEs: "Lo que se le cobra al cliente se separa en cinco conceptos: uso de muelle, estibaje, manipuleo, almacenaje y calada. Cada carga puede tener un precio distinto en cada uno.",
    ejemplo: "Descargar, guardar y despachar una tonelada de fertilizante se cobra unos 30 dólares en total.",
    donde: "Grilla de flujos de cada unidad." },
  { grupo: "El negocio portuario", termino: "Uso de muelle",
    queEs: "Lo que se cobra por ocupar el muelle mientras el barco carga o descarga. En realidad no se vende una tonelada: se vende tiempo de muelle, y se factura por tonelada.",
    ejemplo: "Referencia de la zona: 0,37 dólares por tonelada de registro del buque, por día de estadía.",
    donde: "Columna 'Muelle USD/tn' en la grilla de flujos." },
  { grupo: "El negocio portuario", termino: "Estibaje",
    queEs: "El trabajo de cargar o descargar el barco: grúas, cintas, cuadrillas. Es lo más caro de la operación y lo que más varía entre productos.",
    ejemplo: "Descargar acero se cobra mucho más que embarcar granos, porque es bulto por bulto.",
    donde: "Columna 'Estibaje USD/tn'." },
  { grupo: "El negocio portuario", termino: "Ocupación de muelle",
    queEs: "Qué porcentaje del año está el muelle ocupado. Es la restricción física del negocio: se puede vender todo lo que se quiera, pero si el muelle está lleno no entra un barco más.",
    ejemplo: "Si la ocupación da 85%, el puerto ya está saturado: cualquier demora genera cola de barcos.",
    donde: "Gráfico de ocupación en el Resumen y fila en el flujo consolidado." },
  { grupo: "El negocio portuario", termino: "Parcela",
    queEs: "Cuántas toneladas carga o descarga un barco en esa escala. Cuanto más chica la parcela, más barcos hacen falta para el mismo volumen, y más se ocupa el muelle.",
    ejemplo: "Un granelero puede llevar 27.000 toneladas; uno de fertilizante, 20.000.",
    donde: "Parámetros de ocupación de cada unidad." },
  { grupo: "El negocio portuario", termino: "Sitios de atraque",
    queEs: "Cuántos buques pueden estar amarrados y operando a la vez. Divide la ocupación: con 2 sitios el mismo tráfico ocupa la mitad. Es la variable que decide si hay que construir más muelle.",
    ejemplo: "Con las tres unidades en un solo sitio la ocupación daba 438%; con 3 sitios baja a 59%.",
    donde: "Parámetros generales." },
  { grupo: "El negocio portuario", termino: "Take-or-pay",
    queEs: "Un contrato donde el cliente paga un volumen mínimo aunque no lo use. Le da un piso de facturación al puerto.",
    ejemplo: "El cliente se compromete a 500.000 toneladas: si manda 400.000, paga 500.000 igual.",
    donde: "Parámetros de cada unidad." },
  { grupo: "El negocio portuario", termino: "Rampa (RampUp)",
    queEs: "Qué porcentaje de la capacidad se logra usar en los primeros años, mientras se afinan los procesos y se consiguen clientes. Ningún puerto arranca al 100%.",
    ejemplo: "El primer año se opera al 70% de lo previsto: la rampa es 0,70.",
    donde: "Bloque de rampa en Parámetros generales." },
  { grupo: "El negocio portuario", termino: "Costos comunes y prorrateo",
    queEs: "Gastos que sirven a los tres negocios a la vez. Hay que repartirlos con algún criterio, porque si no ninguno se hace cargo. Lo que depende del muelle se reparte por ocupación, nunca por toneladas.",
    ejemplo: "El dragado cuesta 500 mil al año y se reparte 60% agrograneles, 20% fertilizantes, 20% cargas.",
    donde: "Hoja de Costos comunes." },
  { grupo: "El negocio portuario", termino: "Structuring Fee",
    queEs: "La comisión que se cobra por armar la operación: conseguir los socios, estructurar el financiamiento, tramitar el RIGI. Se cobra una sola vez.",
    ejemplo: "10 millones que cobra un socio y desembolsan los otros tres en partes iguales.",
    donde: "Parámetros generales y panel de Inversores." },
  { grupo: "El negocio portuario", termino: "Pari passu",
    queEs: "Expresión latina: 'en igualdad de condiciones'. Todos los socios ponen y cobran en la misma proporción que su participación, sin que ninguno tenga prioridad.",
    ejemplo: "Un socio con 55% pone el 55% de la inversión y cobra el 55% de lo que sobra.",
    donde: "Panel de Inversores." },
];

export const MANUAL: { titulo: string; parrafos: string[] }[] = [
  { titulo: "Qué pregunta responde esta aplicación", parrafos: [
    "Una sola: si ponemos esta cantidad de plata en construir el puerto, y después lo operamos durante 30 años cobrando estas tarifas, pagando estos costos y estos impuestos, ¿cuánta plata nos devuelve y a qué ritmo? Todo lo demás existe para poder contestar eso con números trazables en lugar de intuición.",
    "La cadena de razonamiento es siempre la misma: toneladas × tarifa = ingresos. Ingresos − costos de operar − canon = EBITDA. EBITDA − desgaste de la inversión = EBIT, que es sobre lo que se paga impuesto. EBIT − impuesto + desgaste (que no era plata) − inversión = flujo de caja. Y el flujo de caja de los 31 años, resumido en un solo número, es la TIR.",
  ]},
  { titulo: "Las tres unidades de negocio", parrafos: [
    "Agrograneles: granos que entran por camión o vagón, se acondicionan, se guardan en silos y se embarcan. Es el negocio de mayor volumen y el de tarifa más baja por tonelada.",
    "Fertilizantes y graneles líquidos: fertilizantes sólidos, UAN y aceites. Se descargan del buque, se guardan en depósito o tanques y se despachan. Menos volumen que granos pero tarifa mucho más alta por tonelada.",
    "Cargas generales: acero, bobinas, mineral de hierro, soda ash, trasbordos y barcazas. Volumen chico, tarifa alta y operación lenta: ocupa mucho muelle por tonelada.",
    "Las tres se calculan con la misma estructura, así que quien entiende una entiende las tres, y el consolidado es una suma directa.",
  ]},
  { titulo: "Los dos métodos de tarifa", parrafos: [
    "Cada unidad elige cómo se calculan sus ingresos, y las dos opciones conviven: se puede tener agrograneles con un método y las otras dos con el otro.",
    "Método 1, grilla de flujos: se enumera cada corriente comercial —por ejemplo, 'entra fertilizante por buque y va a depósito'— con su volumen del primer año, cuánto crece, su techo y las cinco tarifas que se le cobran. El modelo suma todos los flujos. Sirve cuando el negocio es una mezcla de cargas distintas, cada una con su precio.",
    "Método 2, escalonado por volumen: se proyecta un volumen único para toda la unidad y la tarifa baja por escalones a medida que ese volumen sube. Sirve cuando hay un acuerdo comercial con precios por tramo. El campo clave es 'Volumen total a operar del dueño': en cero, todo se cobra a tarifa base porque opera un tercero; con un valor mayor a cero, el dueño opera hasta ese tope con las tarifas por tramo y el excedente vuelve a tarifa base.",
  ]},
  { titulo: "La restricción que más se olvida: el muelle", parrafos: [
    "Se puede vender toda la mercadería del mundo, pero si el muelle está ocupado no entra un barco más. El modelo calcula, para cada unidad, cuántos barcos hacen falta y cuántos días queda amarrado cada uno según la velocidad de carga y el tiempo que se pierde por lluvia o maniobras. Con eso saca qué porcentaje del año está ocupado el muelle.",
    "Si las tres unidades juntas superan el umbral, la aplicación avisa. Por encima de ese nivel cualquier demora genera cola de barcos y el volumen prometido deja de ser creíble: o se construye más muelle —que es más CAPEX— o se rechaza carga.",
    "Por la misma razón, los costos del muelle se reparten entre los negocios por ocupación y no por toneladas: una tonelada de acero ocupa muchísimo más muelle que una de granos, y repartir por tonelada haría que granos subsidie al resto.",
  ]},
  { titulo: "Los impuestos, sin tecnicismos", parrafos: [
    "Todos los impuestos se calculan una sola vez, sobre el resultado de los tres negocios juntos. La razón es simple: quien paga impuestos es la empresa, no cada negocio por separado, y si un negocio pierde plata esa pérdida compensa la ganancia del otro. Las filas de impuesto que aparecen en cada unidad son solo informativas.",
    "Los ahorros de IIBB y de impuesto municipal aparecen como MEMO porque la exención significa que no sale plata, no que entre: no suman al flujo de caja. El IVA de las inversiones también es MEMO: es crédito fiscal, no costo, y tratarlo como costo es el error más común en los modelos de inversión.",
    "El RIGI se trata como un interruptor, no como un supuesto. Hay que correr el modelo prendido y apagado, y presentar las dos TIR. La diferencia entre ambas es exactamente cuánto vale el régimen para este proyecto, y ese es el argumento ante el directorio.",
    "Las alícuotas y los plazos cargados son los vigentes al momento de armar el modelo. Las normas cambian: antes de presentar cualquier número hay que confirmarlas con el asesor impositivo. Esta aplicación hace la cuenta; no es asesoramiento fiscal.",
  ]},
  { titulo: "Cómo interpretar los resultados", parrafos: [
    "EBITDA positivo pero TIR baja: el negocio funciona pero la inversión es demasiado grande para lo que genera. La discusión ahí no es comercial sino de ingeniería y de fases.",
    "EBITDA negativo: el negocio pierde plata operando. Ninguna estructura financiera, ningún beneficio impositivo y ningún plazo más largo lo arreglan. Hay que revisar tarifas o costos.",
    "DSCR por debajo de 1,3: el banco probablemente no preste, o pida garantías adicionales. Se resuelve con menos deuda o más plazo.",
    "Ocupación de muelle por encima del umbral: el modelo está prometiendo un volumen que físicamente no entra. Cualquier TIR calculada sobre ese volumen es ficticia.",
  ]},
  { titulo: "Cómo se guarda el trabajo", parrafos: [
    "Cada vez que tocás un campo, la aplicación recalcula todo al instante, pero nada se guarda hasta que apretás Guardar. Antes de guardar podés ver exactamente qué campos cambiaron, con el valor anterior y el nuevo.",
    "Cada guardado crea una versión nueva, con la lista de cambios, un comentario opcional y los indicadores de ese momento. Nada se pisa ni se borra: el historial completo queda disponible para auditar quién cambió qué supuesto y cuándo.",
    "Se pueden tener varios escenarios en paralelo —por ejemplo, uno con RIGI y otro sin RIGI— y compararlos.",
  ]},
  { titulo: "Qué valores hay que reemplazar", parrafos: [
    "Todo lo que trae el escenario base es preliminar. Como mínimo hay que validar: las tarifas de los cinco rubros y los volúmenes de cada flujo con Comercial; el OPEX fijo y variable de cada unidad, que debería derivarse de dotación por mano y turno, mantenimiento como porcentaje del CAPEX de cada activo y energía, con Operaciones; las curvas de CAPEX con Ingeniería; los porcentajes de prorrateo con Control de Gestión; y el bloque RIGI con el asesor impositivo.",
    "El tipo de cambio oficial y el mínimo mensual del DREI vienen en cero: hay que completarlos, porque sin ellos el DREI se calcula solo por alícuota y subestima el costo.",
  ]},
];
